/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controll.MedicineManager;
import Controll.Navigator;
import Model.Medicine;
import javax.swing.JOptionPane;
/**
 *
 * @author upash
 */
public class AddMed extends javax.swing.JPanel {

    /**
     * Creates new form PAddMed
     */
    public AddMed() {
        initComponents();
        medicineManager = MedicineManager.getInstance();
        loadMedTableFromManager();   //  loads dummy + saved medicines
        MedTable.setDefaultEditor(Object.class, null);
        MedDoseTxtField.setText("mg");
        MedDoseTxtField.setCaretPosition(0); // cursor before "mg"

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MedHome = new javax.swing.JButton();
        AddmedPNG = new javax.swing.JLabel();
        AddmedLogo = new javax.swing.JLabel();
        AddMed = new javax.swing.JLabel();
        MedName = new javax.swing.JLabel();
        MedNameTxtField = new javax.swing.JTextField();
        MedDose = new javax.swing.JLabel();
        MedUse = new javax.swing.JLabel();
        MedDoseTxtField = new javax.swing.JTextField();
        DocRec = new javax.swing.JLabel();
        MedUseTxtField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DocRecTxtArea = new javax.swing.JTextArea();
        MedSave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        MedTable = new javax.swing.JTable();
        Remove = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        SearchBtn = new javax.swing.JButton();
        SearchTxt = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(219, 244, 245));
        jPanel1.setMinimumSize(new java.awt.Dimension(1707, 1607));
        jPanel1.setPreferredSize(new java.awt.Dimension(1707, 1607));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MedHome.setText("Home");
        MedHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedHomeActionPerformed(evt);
            }
        });
        jPanel1.add(MedHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 240, -1, -1));
        jPanel1.add(AddmedPNG, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        AddmedLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        jPanel1.add(AddmedLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        AddMed.setFont(new java.awt.Font("Segoe UI Historic", 3, 36)); // NOI18N
        AddMed.setText("Add Medicine");
        jPanel1.add(AddMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 251, -1));

        MedName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        MedName.setText("Name:");
        jPanel1.add(MedName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));
        jPanel1.add(MedNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 234, 32));

        MedDose.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        MedDose.setText("Medicine Dosage:");
        jPanel1.add(MedDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        MedUse.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        MedUse.setText("Medicine use:");
        jPanel1.add(MedUse, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, -1, -1));

        MedDoseTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MedDoseTxtFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MedDoseTxtFieldKeyTyped(evt);
            }
        });
        jPanel1.add(MedDoseTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 240, 32));

        DocRec.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        DocRec.setText("Doctors recommendation:");
        jPanel1.add(DocRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, -1));
        jPanel1.add(MedUseTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 240, 32));

        DocRecTxtArea.setColumns(20);
        DocRecTxtArea.setRows(5);
        jScrollPane1.setViewportView(DocRecTxtArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 240, 100));

        MedSave.setText("Save");
        MedSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedSaveActionPerformed(evt);
            }
        });
        jPanel1.add(MedSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 670, -1, -1));

        MedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name", "Medicine Dosage"
            }
        ));
        MedTable.setDoubleBuffered(true);
        jScrollPane2.setViewportView(MedTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 740, -1));

        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });
        jPanel1.add(Remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 670, -1, -1));

        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jPanel1.add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, -1, -1));

        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 260, -1, -1));

        SearchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTxtActionPerformed(evt);
            }
        });
        jPanel1.add(SearchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(841, 260, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MedHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedHomeActionPerformed
        // TODO add your handling code here:
        Navigator.showAdminPanel();
    }//GEN-LAST:event_MedHomeActionPerformed

    private void MedSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedSaveActionPerformed
        // TODO add your handling code here:
       String name = MedNameTxtField.getText().trim();
    String dosage = MedDoseTxtField.getText().trim();
    String use = MedUseTxtField.getText().trim();
    String recommendation = DocRecTxtArea.getText().trim();

    //  Validation: empty fields
    if (name.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Medicine name is required!");
        MedNameTxtField.requestFocus();
        return;
    }

    if (dosage.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Medicine dosage is required!");
        MedDoseTxtField.requestFocus();
        return;
    }

    if (use.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Medicine use is required!");
        MedUseTxtField.requestFocus();
        return;
    }

    if (recommendation.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Doctor recommendation is required!");
        DocRecTxtArea.requestFocus();
        return;
    }

    //  Create medicine object
    Medicine medicine = new Medicine(name, dosage, use, recommendation);

    //  Add to manager (Queue + Stack)
    medicineManager.addMedicine(medicine);

    //  Refresh table from manager (prevents duplicates)
    loadMedTableFromManager();

    JOptionPane.showMessageDialog(this,
        "Medicine '" + name + "' added successfully!",
        "Success",
        JOptionPane.INFORMATION_MESSAGE);

    // 🧹 Clear fields
    MedNameTxtField.setText("");
    MedDoseTxtField.setText("");
    MedUseTxtField.setText("");
    DocRecTxtArea.setText("");
    }//GEN-LAST:event_MedSaveActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        // TODO add your handling code here:
        int selectedRow = MedTable.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this,
                "Please select a medicine to delete!",
                "No Selection",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Read selected row data (only name + dose required)
    String name = MedTable.getValueAt(selectedRow, 0).toString();
    String dose = MedTable.getValueAt(selectedRow, 1).toString();

    // Optional: confirm
    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete: " + name + " (" + dose + ")?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    // Remove from manager (must remove from queue + stack)
    boolean removed = medicineManager.removeMedicine(name, dose);

    if (removed) {
        JOptionPane.showMessageDialog(this,
                "Medicine deleted successfully!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);

        // Refresh table
        loadMedTableFromManager();

        // Clear selection and form
        MedTable.clearSelection();
        MedNameTxtField.setText("");
        MedDoseTxtField.setText("");
        MedUseTxtField.setText("");
        DocRecTxtArea.setText("");

    } else {
        JOptionPane.showMessageDialog(this,
                "Failed to delete medicine!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_RemoveActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        // Reload table data from MedicineManager
    loadMedTableFromManager();

    // Clear selection
    MedTable.clearSelection();

    // Clear form fields
    MedNameTxtField.setText("");
    MedDoseTxtField.setText("");
    MedUseTxtField.setText("");
    DocRecTxtArea.setText("");

    JOptionPane.showMessageDialog(
        this,
        "Medicine list refreshed successfully!",
        "Refreshed",
        JOptionPane.INFORMATION_MESSAGE
    );

    }//GEN-LAST:event_RefreshActionPerformed

    private void MedDoseTxtFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MedDoseTxtFieldKeyTyped
        // TODO add your handling code here:
          char c = evt.getKeyChar();

    // Allow only digits
    if (!Character.isDigit(c) && c != '\b') {
        evt.consume(); // ❌ block the character
    }  
    }//GEN-LAST:event_MedDoseTxtFieldKeyTyped

    private void MedDoseTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MedDoseTxtFieldKeyReleased
        // TODO add your handling code here:
         String text = MedDoseTxtField.getText();

    // Remove mg if user tried to edit it
    text = text.replace("mg", "");

    // Re-append mg
    MedDoseTxtField.setText(text + "mg");

    // Keep cursor before mg
    MedDoseTxtField.setCaretPosition(text.length());
    }//GEN-LAST:event_MedDoseTxtFieldKeyReleased

    private void SearchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTxtActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
        performBinarySearch();
    }//GEN-LAST:event_SearchBtnActionPerformed
    
    private void loadMedTableFromManager() {
    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) MedTable.getModel();

    model.setRowCount(0); // clear table

    for (Medicine med : medicineManager.getAllMedicinesFIFO()) {
        model.addRow(new Object[]{ med.getName(), med.getDose() });
    }
}

private void performBinarySearch() {
    String target = SearchTxt.getText().trim();

    if (target.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter medicine name to search!");
        return;
    }

    // 1) Get medicines and sort by name (binary search needs sorted list)
    java.util.List<Medicine> meds = new java.util.ArrayList<>(medicineManager.getAllMedicinesFIFO());
    meds.sort((a, b) -> a.getName().compareToIgnoreCase(b.getName()));

    // 2) Binary search
    int idx = binarySearchByName(meds, target);

    if (idx == -1) {
        JOptionPane.showMessageDialog(this, "Medicine not found!");
        return;
    }

    Medicine found = meds.get(idx);

    // 3) Fill fields
    MedNameTxtField.setText(found.getName());
    MedDoseTxtField.setText(found.getDose());
    MedUseTxtField.setText(found.getUse());
    DocRecTxtArea.setText(found.getDoctorRec());

    // 4) (Optional) highlight row in table
    highlightInTable(found.getName());

    JOptionPane.showMessageDialog(this, "Medicine found!");
}

private int binarySearchByName(java.util.List<Medicine> list, String targetName) {
    int low = 0;
    int high = list.size() - 1;

    while (low <= high) {
        int mid = (low + high) / 2;
        int cmp = list.get(mid).getName().compareToIgnoreCase(targetName);

        if (cmp == 0) return mid;
        if (cmp < 0) low = mid + 1;
        else high = mid - 1;
    }
    return -1;
}

private void highlightInTable(String medName) {
    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) MedTable.getModel();

    for (int i = 0; i < model.getRowCount(); i++) {
        String tableName = model.getValueAt(i, 0).toString();
        if (tableName.equalsIgnoreCase(medName)) {
            MedTable.setRowSelectionInterval(i, i);
            MedTable.scrollRectToVisible(MedTable.getCellRect(i, 0, true));
            break;
        }
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddMed;
    private javax.swing.JLabel AddmedLogo;
    private javax.swing.JLabel AddmedPNG;
    private javax.swing.JLabel DocRec;
    private javax.swing.JTextArea DocRecTxtArea;
    private javax.swing.JLabel MedDose;
    private javax.swing.JTextField MedDoseTxtField;
    private javax.swing.JButton MedHome;
    private javax.swing.JLabel MedName;
    private javax.swing.JTextField MedNameTxtField;
    private javax.swing.JButton MedSave;
    private javax.swing.JTable MedTable;
    private javax.swing.JLabel MedUse;
    private javax.swing.JTextField MedUseTxtField;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton Remove;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField SearchTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    private MedicineManager medicineManager;
}
