/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;
import Controll.Controll;
import Controll.Navigator;
import Controll.PatientQueueController;
import Model.Model;
import javax.swing.JOptionPane;
import Controll.DeletedPatient;
import Controll.DeletedPatient;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author upash
 */
public class AddPatient extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
        public AddPatient() {
        initComponents();
        setupTable();
        PatientQueueController queue = PatientQueueController.getInstance();
        if (queue.isQueueEmpty()) {
        queue.addDummyPatients();
        }
        loadPatientsToTable();

        
    SearchTxt.setForeground(java.awt.Color.GRAY);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AddPatientForm = new javax.swing.JPanel();
        Id = new javax.swing.JLabel();
        IdField = new javax.swing.JTextField();
        Gender = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        AgeField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Age = new javax.swing.JLabel();
        ContactField = new javax.swing.JTextField();
        Address = new javax.swing.JLabel();
        AddressField = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        Name = new javax.swing.JLabel();
        SaveButton = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PatientTable = new javax.swing.JTable();
        SortById = new javax.swing.JButton();
        ShortByName = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        SearchTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(219, 245, 244));
        setPreferredSize(new java.awt.Dimension(1707, 1067));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel2.setText("Add Patient");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, -1, -1));

        Id.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        Id.setText("ID:");

        IdField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        IdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdFieldActionPerformed(evt);
            }
        });
        IdField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IdFieldKeyTyped(evt);
            }
        });

        Gender.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        Gender.setText("Gender:");

        NameField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        AgeField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AgeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AgeFieldKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel6.setText("Contact:");

        Age.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        Age.setText("Age:");

        ContactField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Address.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        Address.setText("Address:");

        AddressField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Male");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");

        Name.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        Name.setText("Name:");

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddPatientFormLayout = new javax.swing.GroupLayout(AddPatientForm);
        AddPatientForm.setLayout(AddPatientFormLayout);
        AddPatientFormLayout.setHorizontalGroup(
            AddPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPatientFormLayout.createSequentialGroup()
                .addGroup(AddPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddPatientFormLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(Id)
                        .addGap(18, 18, 18)
                        .addComponent(IdField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddPatientFormLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(AddPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Gender)
                            .addComponent(Name))
                        .addGap(18, 18, 18)
                        .addGroup(AddPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)))
                    .addGroup(AddPatientFormLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(AddPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Age)
                            .addComponent(jLabel6)
                            .addComponent(Address))
                        .addGap(18, 18, 18)
                        .addGroup(AddPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ContactField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AddPatientFormLayout.createSequentialGroup()
                                .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SaveButton)
                                .addGap(18, 18, 18)
                                .addGroup(AddPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Remove)
                                    .addComponent(Update))))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        AddPatientFormLayout.setVerticalGroup(
            AddPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPatientFormLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(AddPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Id)
                    .addComponent(IdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(AddPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name))
                .addGap(45, 45, 45)
                .addGroup(AddPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(Gender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(AddPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ContactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Age)
                    .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address)
                    .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveButton)
                    .addComponent(Update))
                .addGap(29, 29, 29)
                .addComponent(Remove)
                .addGap(16, 16, 16))
        );

        add(AddPatientForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 670, 500));

        PatientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Gender", "Contact", "Age", "Address"
            }
        ));
        PatientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PatientTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 610, 500));

        SortById.setText("Sort by ID");
        SortById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortByIdActionPerformed(evt);
            }
        });
        add(SortById, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, -1, -1));

        ShortByName.setText("Sort by Name");
        ShortByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShortByNameActionPerformed(evt);
            }
        });
        add(ShortByName, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 260, -1, -1));

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 260, -1, -1));

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 260, -1, -1));

        SearchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTxtActionPerformed(evt);
            }
        });
        add(SearchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 260, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:                                          
        savePatient();   
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void IdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdFieldActionPerformed

    private void IdFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        // Allow only digits (0-9)
        if (!Character.isDigit(c)) {
            evt.consume();  // Block the character
        }
        
        // Optional: Block if already too long (e.g., max 6 digits for ID)
        if (IdField.getText().length() >= 6) {
            evt.consume();
        }
    }//GEN-LAST:event_IdFieldKeyTyped

    private void AgeFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AgeFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        // Allow only digits
        if (!Character.isDigit(c)) {
            evt.consume();
        }
        
        // Optional: Max 3 digits for age (1-150)
        if (AgeField.getText().length() >= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_AgeFieldKeyTyped

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = PatientTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a patient to update!", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String id = IdField.getText().trim();
        String name = NameField.getText().trim();
        String gender = getSelectedGender();
        String contact = ContactField.getText().trim();
        String ageText = AgeField.getText().trim();
        String address = AddressField.getText().trim();

        // Validation (same as save)
        if (name.isEmpty() || gender.isEmpty() || contact.isEmpty() || 
            ageText.isEmpty() || address.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Contact validation
        if (!contact.matches("\\d{10,15}")) {
            JOptionPane.showMessageDialog(this, 
                "Invalid contact number!\nMust be 10 digits only.", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            int age = Integer.parseInt(ageText);
            if (age <= 0 || age > 150) {
                JOptionPane.showMessageDialog(this, "Age must be between 1 and 150!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Prepare updated data array
            String[] updatedData = new String[]{
                id, name, gender, contact, address, String.valueOf(age)
            };

            // Update in queue (logical index = selectedRow)
            PatientQueueController queue = PatientQueueController.getInstance();
            boolean updated = queue.updatePatient(selectedRow, updatedData);
            queue.backupQueue();
            
            if (updated) {
                JOptionPane.showMessageDialog(this, "Patient updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

                // Refresh table to show changes
                loadPatientsToTable();

                // Clear selection and form
                PatientTable.clearSelection();
                clearForm(); // Call your clear method or manually clear
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update patient!", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Age must be a valid number!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void PatientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = PatientTable.getSelectedRow();
        if (selectedRow == -1) return; // No row selected

        // Get data from selected row
        String id = tableModel.getValueAt(selectedRow, 0).toString();
        String name = tableModel.getValueAt(selectedRow, 1).toString();
        String gender = tableModel.getValueAt(selectedRow, 2).toString();
        String contact = tableModel.getValueAt(selectedRow, 3).toString();
        String age = tableModel.getValueAt(selectedRow, 4).toString();
        String address = tableModel.getValueAt(selectedRow, 5).toString();

        // Fill form
        IdField.setText(id);
        NameField.setText(name);
        ContactField.setText(contact);
        AgeField.setText(age);
        AddressField.setText(address);

        // Set gender radio buttons
        if (gender.equals("Male")) {
            jRadioButton1.setSelected(true);
            jRadioButton2.setSelected(false);
        } else if (gender.equals("Female")) {
            jRadioButton1.setSelected(false);
            jRadioButton2.setSelected(true);
        } else {
            buttonGroup1.clearSelection();
        }

        // Optional: make ID field non-editable during update
        IdField.setEditable(false);
    }//GEN-LAST:event_PatientTableMouseClicked

    private void SortByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortByIdActionPerformed
        // TODO add your handling code here:
        // Get the queue controller instance
        PatientQueueController queue = PatientQueueController.getInstance();
        
        // Sort the queue by ID (ascending)
        queue.sortQueueById();
        
        // Refresh the table to show the sorted order
        loadPatientsToTable();
    }//GEN-LAST:event_SortByIdActionPerformed

    private void ShortByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShortByNameActionPerformed
        // TODO add your handling code here:
        PatientQueueController queue = PatientQueueController.getInstance();
        queue.sortQueueByName();
        loadPatientsToTable();
    }//GEN-LAST:event_ShortByNameActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        // TODO add your handling code here:
 // Get selected row
    int row = PatientTable.getSelectedRow();
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Select a patient to delete!");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) PatientTable.getModel();

    // Get patient details from the selected row
    String patientId = model.getValueAt(row, 0).toString();
    String patientName = model.getValueAt(row, 1).toString();
    
    String[] deleted = new String[]{
    model.getValueAt(row, 0).toString(),
    model.getValueAt(row, 1).toString(),
    model.getValueAt(row, 2).toString(),
    model.getValueAt(row, 3).toString(),
    model.getValueAt(row, 4).toString(),
    model.getValueAt(row, 5).toString()
};
DeletedPatient.getInstance().push(deleted);


    // ✅ Remove from queue
    PatientQueueController queue = PatientQueueController.getInstance();
    
    int queueSize = queue.getQueueSize();
    java.util.List<String[]> keptPatients = new java.util.ArrayList<>();

    // Dequeue all patients
    for (int i = 0; i < queueSize; i++) {
        String[] p = queue.dequeuePatient();
        if (p != null && !p[0].equals(patientId)) {
            keptPatients.add(p); // Keep patients that don't match
        }
    }

    // Re-enqueue kept patients
    for (String[] p : keptPatients) {
        queue.enqueuePatient(p[0], p[1], p[2], p[3], p[4], p[5]);
    }

    JOptionPane.showMessageDialog(this, 
        "Patient " + patientName + " (ID: " + patientId + ") removed!\n" +
        "Added to deleted patients stack.\n" +
        "Stack size: " + DeletedPatient.getInstance().getSize(), 
        "Success", JOptionPane.INFORMATION_MESSAGE);

    // Refresh table and clear form
    loadPatientsToTable();
    clearForm();
    }//GEN-LAST:event_RemoveActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        Navigator.showAdminPanel();
    }//GEN-LAST:event_HomeActionPerformed

    private void SearchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTxtActionPerformed
        // TODO add your handling code here:
        performSearch();
    }//GEN-LAST:event_SearchTxtActionPerformed
   
    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        performSearch();
    }//GEN-LAST:event_SearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddPatientForm;
    private javax.swing.JLabel Address;
    private javax.swing.JTextField AddressField;
    private javax.swing.JLabel Age;
    private javax.swing.JTextField AgeField;
    private javax.swing.JTextField ContactField;
    private javax.swing.JLabel Gender;
    private javax.swing.JButton Home;
    private javax.swing.JLabel Id;
    private javax.swing.JTextField IdField;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField NameField;
    private javax.swing.JTable PatientTable;
    private javax.swing.JButton Remove;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton Search;
    private javax.swing.JTextField SearchTxt;
    private javax.swing.JButton ShortByName;
    private javax.swing.JButton SortById;
    private javax.swing.JButton Update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
       
    private DefaultTableModel tableModel;
        
    private void setupTable() {
    tableModel = new DefaultTableModel(
        new Object[][] {},
        new String[] {"ID", "Name", "Gender", "Contact", "Age", "Address"}
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // disables editing for all cells
        }
    };

    PatientTable.setModel(tableModel);

    }
    private void loadPatientsToTable() {
        tableModel.setRowCount(0);
        PatientQueueController queue = PatientQueueController.getInstance();
        String[][] queuePatients = queue.getAllQueuePatients();

        for (String[] p : queuePatients) {
            tableModel.addRow(new Object[]{
                p[0],  // ID
                p[1],  // Name
                p[2],  // Gender
                p[3],  // Contact
                p[5],  // Age
                p[4]   // Address
            });
        }
}


    private String getSelectedGender() {
        if (jRadioButton1.isSelected()) return "Male";
        if (jRadioButton2.isSelected()) return "Female";
        return "";
    }

       private void savePatient() {
        String idText = IdField.getText().trim();
        String name = NameField.getText().trim();
        String gender = getSelectedGender();
        String contact = ContactField.getText().trim();
        String ageText = AgeField.getText().trim();
        String address = AddressField.getText().trim();

        // Validation
        if (idText.isEmpty() || name.isEmpty() || gender.isEmpty() ||
            contact.isEmpty() || ageText.isEmpty() || address.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            int id = Integer.parseInt(idText);

            if (id <= 0) {
                JOptionPane.showMessageDialog(this, "ID must be a positive number!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Check for duplicate ID
            if (Model.getPatientById(id) != null) {
                JOptionPane.showMessageDialog(this, "Patient with this ID already exists!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (!contact.matches("\\d{10,15}")) {
                JOptionPane.showMessageDialog(this, 
                    "Invalid contact number!\nMust contain only digits and be 10-15 digits long.", 
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            int age = Integer.parseInt(ageText);
            if (age <= 0) {
                JOptionPane.showMessageDialog(this, "Age must be a positive number!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Create and add patient to permanent list
            Model patient = new Model(id, name, gender, contact, age, address);
            Model.addPatient(patient);

            // NEW: Add to queue so it appears in table immediately
            PatientQueueController queue = PatientQueueController.getInstance();
            queue.enqueuePatient(String.valueOf(id), name, gender, contact, address, String.valueOf(age));
            queue.backupQueue();
            
            JOptionPane.showMessageDialog(this, "Patient added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Clear form
            IdField.setText("");
            NameField.setText("");
            ContactField.setText("");
            AgeField.setText("");
            AddressField.setText("");
            buttonGroup1.clearSelection();

            // Refresh table - now shows the new patient
            loadPatientsToTable();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID and Age must be valid numbers!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void clearForm() {
        NameField.setText("");
        ContactField.setText("");
        AgeField.setText("");
        AddressField.setText("");
        buttonGroup1.clearSelection();
        IdField.setEditable(true);
        PatientTable.clearSelection();
    }
   private void performSearch() {
    String searchId = SearchTxt.getText().trim();

    if (searchId.isEmpty() || searchId.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter Patient ID to search");
        return;
    }

    String[] patient = PatientQueueController
                            .getInstance()
                            .findPatientById(searchId);

    if (patient == null) {
        JOptionPane.showMessageDialog(this, "Patient not found");
        return;
    }

    // Fill fields
    IdField.setText(patient[0]);
    NameField.setText(patient[1]);

    String gender = patient[2];
    if ("Male".equalsIgnoreCase(gender)) {
        jRadioButton1.setSelected(true);
    } else if ("Female".equalsIgnoreCase(gender)) {
        jRadioButton2.setSelected(true);
    } else {
        buttonGroup1.clearSelection();
    }

    ContactField.setText(patient[3]);
    AddressField.setText(patient[4]);
    AgeField.setText(patient[5]);

    JOptionPane.showMessageDialog(this, "Patient found!");
}
}
