/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author upash
 */
public class AdminPannel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminPannel.class.getName());

    /**
     * Creates new form AdminPannel
     */
    public AdminPannel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminPage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AdminPageMain = new javax.swing.JPanel();
        AddPanel = new javax.swing.JPanel();
        AddPic = new javax.swing.JLabel();
        Addtxt = new javax.swing.JLabel();
        Checkup = new javax.swing.JPanel();
        CheckupPic = new javax.swing.JLabel();
        Checkuptxt = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        ReportPanel = new javax.swing.JPanel();
        ReportPic = new javax.swing.JLabel();
        Patienttxt = new javax.swing.JLabel();
        MedPanel = new javax.swing.JPanel();
        MedPic = new javax.swing.JLabel();
        Medtxt = new javax.swing.JLabel();
        Poweroff = new javax.swing.JPanel();
        Powerofftxt = new javax.swing.JLabel();
        Poweroffpic = new javax.swing.JLabel();
        Adminpagebg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1707, 1067));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminPage.setBackground(new java.awt.Color(219, 244, 241));
        AdminPage.setMinimumSize(new java.awt.Dimension(1707, 1067));
        AdminPage.setPreferredSize(new java.awt.Dimension(1707, 1067));
        AdminPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        AdminPage.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        AdminPageMain.setBackground(new java.awt.Color(219, 244, 241));
        AdminPageMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddPanel.setBackground(new java.awt.Color(255, 255, 255));
        AddPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        AddPanel.setMinimumSize(new java.awt.Dimension(500, 500));
        AddPanel.setPreferredSize(new java.awt.Dimension(200, 200));

        AddPic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/patient.png"))); // NOI18N
        AddPic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddPicMouseEntered(evt);
            }
        });

        Addtxt.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        Addtxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Addtxt.setText("Add Patients");
        Addtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddtxtMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout AddPanelLayout = new javax.swing.GroupLayout(AddPanel);
        AddPanel.setLayout(AddPanelLayout);
        AddPanelLayout.setHorizontalGroup(
            AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPanelLayout.createSequentialGroup()
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(AddPic, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddPanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(Addtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddPanelLayout.setVerticalGroup(
            AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddPic, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Addtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        AdminPageMain.add(AddPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 300, 280));

        Checkup.setBackground(new java.awt.Color(255, 255, 255));
        Checkup.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        Checkup.setMinimumSize(new java.awt.Dimension(500, 500));
        Checkup.setPreferredSize(new java.awt.Dimension(200, 200));
        Checkup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CheckupPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check-up.png"))); // NOI18N
        CheckupPic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CheckupPicMouseEntered(evt);
            }
        });
        Checkup.add(CheckupPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        Checkuptxt.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        Checkuptxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Checkuptxt.setText("Check up");
        Checkuptxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CheckuptxtMouseEntered(evt);
            }
        });
        Checkup.add(Checkuptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        AdminPageMain.add(Checkup, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 300, 280));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jPanel9.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel9.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        AdminPageMain.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 300, 270));

        ReportPanel.setBackground(new java.awt.Color(255, 255, 255));
        ReportPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        ReportPanel.setMinimumSize(new java.awt.Dimension(500, 500));
        ReportPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        ReportPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReportPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/medical_report.png"))); // NOI18N
        ReportPic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReportPicMouseEntered(evt);
            }
        });
        ReportPanel.add(ReportPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        Patienttxt.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        Patienttxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Patienttxt.setText("Patient Report");
        Patienttxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PatienttxtMouseEntered(evt);
            }
        });
        ReportPanel.add(Patienttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        AdminPageMain.add(ReportPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 300, 260));

        MedPanel.setBackground(new java.awt.Color(255, 255, 255));
        MedPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        MedPanel.setMinimumSize(new java.awt.Dimension(500, 500));
        MedPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        MedPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MedPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/drug.png"))); // NOI18N
        MedPic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MedPicMouseEntered(evt);
            }
        });
        MedPanel.add(MedPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        Medtxt.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        Medtxt.setText("Add medicine");
        Medtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MedtxtMouseEntered(evt);
            }
        });
        MedPanel.add(Medtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        AdminPageMain.add(MedPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 300, 260));

        Poweroff.setBackground(new java.awt.Color(255, 255, 255));
        Poweroff.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        Poweroff.setMinimumSize(new java.awt.Dimension(500, 500));
        Poweroff.setPreferredSize(new java.awt.Dimension(200, 200));
        Poweroff.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Powerofftxt.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        Powerofftxt.setText("Power off");
        Powerofftxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PowerofftxtMouseEntered(evt);
            }
        });
        Poweroff.add(Powerofftxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        Poweroffpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/turn-off.png"))); // NOI18N
        Poweroffpic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PoweroffpicMouseEntered(evt);
            }
        });
        Poweroff.add(Poweroffpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        AdminPageMain.add(Poweroff, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, 300, 260));

        AdminPage.add(AdminPageMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1200, 680));

        Adminpagebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AdminBg.png"))); // NOI18N
        AdminPage.add(Adminpagebg, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 270, 500, 480));

        getContentPane().add(AdminPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1707, 1067));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddPicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddPicMouseEntered
        // TODO add your handling code here:
        AddPic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_AddPicMouseEntered

    private void AddtxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddtxtMouseEntered
        // TODO add your handling code here:
        Addtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_AddtxtMouseEntered

    private void ReportPicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportPicMouseEntered
        // TODO add your handling code here:
        ReportPic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_ReportPicMouseEntered

    private void PatienttxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatienttxtMouseEntered
        // TODO add your handling code here:
        Patienttxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_PatienttxtMouseEntered

    private void CheckupPicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckupPicMouseEntered
        // TODO add your handling code here:
        CheckupPic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_CheckupPicMouseEntered

    private void CheckuptxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckuptxtMouseEntered
        // TODO add your handling code here:
        Checkuptxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_CheckuptxtMouseEntered

    private void MedPicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedPicMouseEntered
        // TODO add your handling code here:
        MedPic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_MedPicMouseEntered

    private void MedtxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedtxtMouseEntered
        // TODO add your handling code here:
        Medtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_MedtxtMouseEntered

    private void PoweroffpicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PoweroffpicMouseEntered
        // TODO add your handling code here:
        Poweroffpic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_PoweroffpicMouseEntered

    private void PowerofftxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PowerofftxtMouseEntered
        // TODO add your handling code here:
        Powerofftxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_PowerofftxtMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminPannel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddPanel;
    private javax.swing.JLabel AddPic;
    private javax.swing.JLabel Addtxt;
    private javax.swing.JPanel AdminPage;
    private javax.swing.JPanel AdminPageMain;
    private javax.swing.JLabel Adminpagebg;
    private javax.swing.JPanel Checkup;
    private javax.swing.JLabel CheckupPic;
    private javax.swing.JLabel Checkuptxt;
    private javax.swing.JPanel MedPanel;
    private javax.swing.JLabel MedPic;
    private javax.swing.JLabel Medtxt;
    private javax.swing.JLabel Patienttxt;
    private javax.swing.JPanel Poweroff;
    private javax.swing.JLabel Poweroffpic;
    private javax.swing.JLabel Powerofftxt;
    private javax.swing.JPanel ReportPanel;
    private javax.swing.JLabel ReportPic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
