/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author upash
 */
public class CheckUp extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CheckUp.class.getName());

    /**
     * Creates new form AddMed
     */
    public CheckUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Addpatientbg = new javax.swing.JPanel();
        AddpatientLogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AddPatientPanel = new javax.swing.JPanel();
        Addpatientxt = new javax.swing.JLabel();
        Patientpanel = new javax.swing.JPanel();
        ID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Suggestiontxt = new javax.swing.JTextArea();
        MedicineCB = new javax.swing.JComboBox<>();
        Amount = new javax.swing.JLabel();
        PatientCB = new javax.swing.JComboBox<>();
        Medicinepick = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        List = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MedListtxt = new javax.swing.JTextArea();
        MedPagesave = new javax.swing.JButton();
        Home = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Addpatientbg.setBackground(new java.awt.Color(219, 245, 241));
        Addpatientbg.setMinimumSize(new java.awt.Dimension(1707, 1067));
        Addpatientbg.setPreferredSize(new java.awt.Dimension(1707, 1067));
        Addpatientbg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddpatientLogo.setBackground(new java.awt.Color(219, 245, 241));
        AddpatientLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        AddpatientLogo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 22, -1, -1));

        Addpatientbg.add(AddpatientLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        AddPatientPanel.setBackground(new java.awt.Color(219, 245, 241));

        Addpatientxt.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        Addpatientxt.setText("Add Medicine");

        javax.swing.GroupLayout AddPatientPanelLayout = new javax.swing.GroupLayout(AddPatientPanel);
        AddPatientPanel.setLayout(AddPatientPanelLayout);
        AddPatientPanelLayout.setHorizontalGroup(
            AddPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPatientPanelLayout.createSequentialGroup()
                .addGap(696, 696, 696)
                .addComponent(Addpatientxt)
                .addContainerGap(770, Short.MAX_VALUE))
        );
        AddPatientPanelLayout.setVerticalGroup(
            AddPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPatientPanelLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(Addpatientxt)
                .addGap(18, 18, 18))
        );

        Addpatientbg.add(AddPatientPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 0, 1700, 150));

        Patientpanel.setBackground(new java.awt.Color(255, 255, 255));

        ID.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        ID.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel2.setText("Doctors Perscription:");

        Suggestiontxt.setColumns(20);
        Suggestiontxt.setRows(5);
        jScrollPane1.setViewportView(Suggestiontxt);

        MedicineCB.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        MedicineCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Amount.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        Amount.setText("Amount:");

        PatientCB.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        PatientCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Medicinepick.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        Medicinepick.setText("Select Medicine:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        List.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        List.setText("MedList");

        MedListtxt.setColumns(20);
        MedListtxt.setRows(5);
        jScrollPane2.setViewportView(MedListtxt);

        MedPagesave.setText("Save");
        MedPagesave.setToolTipText("");

        javax.swing.GroupLayout PatientpanelLayout = new javax.swing.GroupLayout(Patientpanel);
        Patientpanel.setLayout(PatientpanelLayout);
        PatientpanelLayout.setHorizontalGroup(
            PatientpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientpanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PatientpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MedPagesave)
                    .addGroup(PatientpanelLayout.createSequentialGroup()
                        .addGroup(PatientpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(ID))
                        .addGap(18, 18, 18)
                        .addGroup(PatientpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PatientCB, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addGroup(PatientpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PatientpanelLayout.createSequentialGroup()
                        .addGroup(PatientpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Amount)
                            .addComponent(Medicinepick))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PatientpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MedicineCB, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PatientpanelLayout.createSequentialGroup()
                        .addComponent(List)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(123, 123, 123))
        );
        PatientpanelLayout.setVerticalGroup(
            PatientpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PatientpanelLayout.createSequentialGroup()
                .addGroup(PatientpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PatientpanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(PatientpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ID)
                            .addComponent(MedicineCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatientCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Medicinepick))
                        .addGroup(PatientpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PatientpanelLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addGap(174, 174, 174))
                            .addGroup(PatientpanelLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(PatientpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Amount)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(PatientpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(List)
                                    .addComponent(jScrollPane2)))))
                    .addGroup(PatientpanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(MedPagesave)
                .addGap(59, 59, 59))
        );

        Addpatientbg.add(Patientpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 1390, 490));

        Home.setText("Home");
        Addpatientbg.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Addpatientbg, javax.swing.GroupLayout.PREFERRED_SIZE, 1713, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Addpatientbg, javax.swing.GroupLayout.PREFERRED_SIZE, 1073, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CheckUp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddPatientPanel;
    private javax.swing.JPanel AddpatientLogo;
    private javax.swing.JPanel Addpatientbg;
    private javax.swing.JLabel Addpatientxt;
    private javax.swing.JLabel Amount;
    private javax.swing.JButton Home;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel List;
    private javax.swing.JTextArea MedListtxt;
    private javax.swing.JButton MedPagesave;
    private javax.swing.JComboBox<String> MedicineCB;
    private javax.swing.JLabel Medicinepick;
    private javax.swing.JComboBox<String> PatientCB;
    private javax.swing.JPanel Patientpanel;
    private javax.swing.JTextArea Suggestiontxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
