/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import javax.swing.JOptionPane;
import Controll.Controll;
import Model.Model;
import static Model.Model.allConstants.LOGIN_KEY;
import static Model.Model.allConstants.USER_KEY;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;



/**
 *
 * @author upash
 */
public class LoginPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginPage.class.getName());
    private Object LoginKey;
    
    /**
     * Creates new form NewJFrame
     */
    public LoginPage() {
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Userfield = new javax.swing.JTextField();
        Passfield = new javax.swing.JPasswordField();
        LoginpageReg = new javax.swing.JButton();
        LoginpageLog = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Pass = new javax.swing.JLabel();
        Logintxt = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        LoginBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1707, 1067));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1707, 1067));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Userfield.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        Userfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserfieldActionPerformed(evt);
            }
        });
        jPanel1.add(Userfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 490, 150, -1));

        Passfield.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jPanel1.add(Passfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 540, 150, -1));

        LoginpageReg.setBackground(new java.awt.Color(0, 51, 255));
        LoginpageReg.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        LoginpageReg.setText("Register");
        LoginpageReg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginpageReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginpageRegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginpageRegMouseExited(evt);
            }
        });
        LoginpageReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginpageRegActionPerformed(evt);
            }
        });
        jPanel1.add(LoginpageReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 640, -1, -1));

        LoginpageLog.setBackground(new java.awt.Color(0, 51, 255));
        LoginpageLog.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        LoginpageLog.setText("Login");
        LoginpageLog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginpageLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginpageLogMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginpageLogMouseExited(evt);
            }
        });
        LoginpageLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginpageLogActionPerformed(evt);
            }
        });
        jPanel1.add(LoginpageLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 600, 100, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 300, 170));

        Pass.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        Pass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pass.setText("Password:");
        jPanel1.add(Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 540, -1, -1));

        Logintxt.setFont(new java.awt.Font("Segoe UI Emoji", 3, 36)); // NOI18N
        Logintxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logintxt.setText("LOGIN PAGE");
        jPanel1.add(Logintxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 270, -1));

        User.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        User.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        User.setText("Username:");
        jPanel1.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, -1, 40));

        LoginBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/registerimage.png"))); // NOI18N
        jPanel1.add(LoginBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -250, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserfieldActionPerformed

    private void LoginpageLogMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginpageLogMouseEntered
        // TODO add your handling code here:
        LoginpageLog.setBackground(new Color(0,102, 255));
    }//GEN-LAST:event_LoginpageLogMouseEntered

    private void LoginpageLogMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginpageLogMouseExited
        // TODO add your handling code here:
        LoginpageLog.setBackground(new Color(0,51,255));
    }//GEN-LAST:event_LoginpageLogMouseExited

    private void LoginpageRegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginpageRegMouseEntered
        // TODO add your handling code here:
        LoginpageReg.setBackground(new Color(0,102, 255));
    }//GEN-LAST:event_LoginpageRegMouseEntered

    private void LoginpageRegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginpageRegMouseExited
        // TODO add your handling code here:
        LoginpageReg.setBackground(new Color(0,51,255));
    }//GEN-LAST:event_LoginpageRegMouseExited

    private void LoginpageLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginpageLogActionPerformed
        // TODO add your handling code here:
        
      String password = new String(Passfield.getPassword());
      String username = Userfield.getText();
      if(password.equals(LOGIN_KEY) && username.equals(USER_KEY)) {
    // Password is correct
    javax.swing.JOptionPane.showMessageDialog(this, "Login successful!");
    // Optionally open your HomePage:
    AdminPannel admin = new AdminPannel();
    admin.setVisible(true);
     // close login page
} else {
    // Password incorrect
    javax.swing.JOptionPane.showMessageDialog(this, "Invalid password or username. Try again.");
}
    }//GEN-LAST:event_LoginpageLogActionPerformed

    private void LoginpageRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginpageRegActionPerformed
        // TODO add your handling code here:
        Register register = new Register();
        register.setvisible(true);
        this.dispose();
    }//GEN-LAST:event_LoginpageRegActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginPage().setVisible(true));
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoginBackground;
    private javax.swing.JButton LoginpageLog;
    private javax.swing.JButton LoginpageReg;
    private javax.swing.JLabel Logintxt;
    private javax.swing.JLabel Pass;
    private javax.swing.JPasswordField Passfield;
    private javax.swing.JLabel User;
    private javax.swing.JTextField Userfield;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    public javax.swing.JButton getLoginButton() {
    return LoginpageLog; // your login button
}

    public String getPassword() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    


}
