/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controll.Navigator;
import Controll.PatientQueueController;
import Controll.PrescriptionStore;

/**
 *
 * @author upash
 */
public class PatientReport extends javax.swing.JPanel {
private final String patientId;
    /**
     * Creates new form PatientReport
     */
     

    public PatientReport(String patientId) {
        this.patientId = patientId;
        initComponents();
        setReadOnly();
        loadReport();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void setReadOnly() {
        
        initComponents();
        setReadOnly();
    }
    private void loadReport() {
       if (patientId == null || patientId.trim().isEmpty()) {
            PatientDtail.setText("No Patient ID provided.");
            PatientDtail.setText("");
            return;
        }

        PatientQueueController queue = PatientQueueController.getInstance();
        String[] p = queue.findPatientById(patientId);

        if (p != null) {
            PatientDtail.setText(
                    "Patient ID: " + p[0] + "\n" +
                    "Name: " + p[1] + "\n" +
                    "Gender: " + p[2] + "\n" +
                    "Contact: " + p[3] + "\n" +
                    "Address: " + p[4] + "\n" +
                    "Age: " + p[5]
            );
        } else {
            PatientDtail.setText("No patient found for ID: " + patientId);
        }

        PrescriptionStore.Record r =
                PrescriptionStore.getInstance().get(patientId);

        if (r != null) {
            PatientDtail.setText(
                    "Doctor Recommendation:\n" +
                    r.doctorPrescription + "\n\n" +
                    "Medicines:\n" +
                    r.medicineDetails
            );
        } else {
            PatientDtail.setText("No prescription available.");
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PatientDtail = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        DeletePatient = new javax.swing.JTextArea();
        DeletedPatient = new javax.swing.JLabel();
        PatientHistory = new javax.swing.JLabel();
        HomePR = new javax.swing.JButton();

        setBackground(new java.awt.Color(219, 245, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel2.setText("Patient Report");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, -1, -1));

        PatientDtail.setColumns(20);
        PatientDtail.setRows(5);
        jScrollPane1.setViewportView(PatientDtail);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 660, 430));

        DeletePatient.setColumns(20);
        DeletePatient.setRows(5);
        jScrollPane2.setViewportView(DeletePatient);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, 480, 430));

        DeletedPatient.setBackground(new java.awt.Color(219, 245, 244));
        DeletedPatient.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        DeletedPatient.setText("Deleted patient");
        add(DeletedPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 320, -1, -1));

        PatientHistory.setBackground(new java.awt.Color(219, 245, 244));
        PatientHistory.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        PatientHistory.setText("Patient history");
        add(PatientHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        HomePR.setText("Home");
        HomePR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomePRActionPerformed(evt);
            }
        });
        add(HomePR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 320, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void HomePRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomePRActionPerformed
        // TODO add your handling code here:
         Navigator.showAdminPanel();
    }//GEN-LAST:event_HomePRActionPerformed
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DeletePatient;
    private javax.swing.JLabel DeletedPatient;
    private javax.swing.JButton HomePR;
    private javax.swing.JTextArea PatientDtail;
    private javax.swing.JLabel PatientHistory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
