/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.MedicineManager;
import Controller.Navigator;
import Controller.PatientQueueController;
import Models.Medicine;
import Controller.PrescriptionStore;



/**
 *
 * @author upash
 */
public class PCheckup extends javax.swing.JPanel {

    /**
     * Creates new form PCheckup
     */
    public PCheckup() {
        initComponents();
        medicineManager = MedicineManager.getInstance();
        populatePatientComboBox();
        loadMedicinesToComboBox();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Patientpanel = new javax.swing.JPanel();
        ID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Suggestiontxt = new javax.swing.JTextArea();
        MedicineCB = new javax.swing.JComboBox<>();
        PatientCB = new javax.swing.JComboBox<>();
        Medicinepick = new javax.swing.JLabel();
        List = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MedListtxt = new javax.swing.JTextArea();
        MedPagesave = new javax.swing.JButton();
        AddBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(219, 245, 244));
        setPreferredSize(new java.awt.Dimension(1707, 1067));

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel2.setText("Check Up");

        Patientpanel.setBackground(new java.awt.Color(255, 255, 255));

        ID.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        ID.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel3.setText("Doctors Perscription:");

        Suggestiontxt.setColumns(20);
        Suggestiontxt.setRows(5);
        jScrollPane1.setViewportView(Suggestiontxt);

        MedicineCB.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        MedicineCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        PatientCB.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        PatientCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PatientCB.setSelectedItem(ID);
        PatientCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientCBActionPerformed(evt);
            }
        });

        Medicinepick.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        Medicinepick.setText("Select Medicine:");

        List.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        List.setText("Details:");

        MedListtxt.setColumns(20);
        MedListtxt.setRows(5);
        jScrollPane2.setViewportView(MedListtxt);

        MedPagesave.setText("Save");
        MedPagesave.setToolTipText("");
        MedPagesave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedPagesaveActionPerformed(evt);
            }
        });

        AddBtn.setText("Add");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PatientpanelLayout = new javax.swing.GroupLayout(Patientpanel);
        Patientpanel.setLayout(PatientpanelLayout);
        PatientpanelLayout.setHorizontalGroup(
            PatientpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientpanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PatientpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MedPagesave)
                    .addGroup(PatientpanelLayout.createSequentialGroup()
                        .addGroup(PatientpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(ID))
                        .addGap(18, 18, 18)
                        .addGroup(PatientpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatientCB, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addGroup(PatientpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PatientpanelLayout.createSequentialGroup()
                        .addComponent(Medicinepick)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MedicineCB, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PatientpanelLayout.createSequentialGroup()
                        .addComponent(List)
                        .addGap(18, 18, 18)
                        .addGroup(PatientpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddBtn)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(123, 123, 123))
        );
        PatientpanelLayout.setVerticalGroup(
            PatientpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PatientpanelLayout.createSequentialGroup()
                .addGroup(PatientpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PatientpanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(PatientpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ID)
                            .addComponent(MedicineCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatientCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Medicinepick))
                        .addGroup(PatientpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PatientpanelLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addGap(174, 174, 174))
                            .addGroup(PatientpanelLayout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addGroup(PatientpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(List)
                                    .addComponent(jScrollPane2)))))
                    .addGroup(PatientpanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PatientpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MedPagesave)
                    .addComponent(AddBtn))
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(443, 443, 443)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 285, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Patientpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(Home)
                .addGap(45, 45, 45)
                .addComponent(Patientpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PatientCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientCBActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        Navigator.showAdminPanel();
    }//GEN-LAST:event_HomeActionPerformed

    private void MedPagesaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedPagesaveActionPerformed
        // TODO add your handling code here:
       String patientId = (String) PatientCB.getSelectedItem();

    if (patientId == null || patientId.equals("No patients in queue")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Select a valid Patient ID!");
        return;
    }

    String doctorRec = Suggestiontxt.getText().trim();
    String medicineDetails = MedListtxt.getText().trim();

    if (doctorRec.isEmpty() && medicineDetails.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Enter prescription or medicine details!");
        return;
    }

    //  SAVE for this specific patient
    PrescriptionStore.getInstance().save(patientId, doctorRec, medicineDetails);

    javax.swing.JOptionPane.showMessageDialog(
        this,
        "Prescription saved for Patient ID: " + patientId
    );

    // Optional: clear fields
    Suggestiontxt.setText("");
    MedListtxt.setText("");
    
    }//GEN-LAST:event_MedPagesaveActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        
     String selected = (String) MedicineCB.getSelectedItem();

    if (selected == null || selected.equals("No medicines available")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a medicine!");
        return;
    }

    // ✅ Extract name from "Name (Dosage)"
    String medicineName = selected;
    int idx = selected.indexOf(" (");
    if (idx != -1) {
        medicineName = selected.substring(0, idx).trim();
    }

    String details = getMedicineDetails(medicineName);

    MedListtxt.append(details + "\n");
    }//GEN-LAST:event_AddBtnActionPerformed
    
    private String getMedicineDetails(String medicineName) {
    Medicine med = findMedicineByName(medicineName);

    if (med == null) {
        return "Medicine not found: " + medicineName;
    }

    String rec = med.getDoctorRec();
    if (rec == null || rec.trim().isEmpty()) {
        rec = "N/A";
    }

    return med.getName()
            + "\nDose: " + med.getDose()
            + "\nUse: " + med.getUse()
            + "\nDoctor Recommendation: " + rec
            + "\n----------------------";
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton Home;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel List;
    private javax.swing.JTextArea MedListtxt;
    private javax.swing.JButton MedPagesave;
    private javax.swing.JComboBox<String> MedicineCB;
    private javax.swing.JLabel Medicinepick;
    private javax.swing.JComboBox<String> PatientCB;
    private javax.swing.JPanel Patientpanel;
    private javax.swing.JTextArea Suggestiontxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    private PatientQueueController queueController;
    private MedicineManager medicineManager;
    
        private void populatePatientComboBox() {
        PatientCB.removeAllItems(); // Clear old items

        PatientQueueController queue = PatientQueueController.getInstance();
        String[][] queuePatients = queue.getAllQueuePatients();

        if (queuePatients.length == 0) {
            PatientCB.addItem("No patients in queue");
            return;
        }

        // Add only the patient IDs
        for (String[] patient : queuePatients) {
            String id = patient[0]; // ID is in column 0
            PatientCB.addItem(id);
        }
        if (PatientCB.getItemCount() > 0) {
    PatientCB.setSelectedIndex(0);
}

    }
        
    @Override
public void setVisible(boolean visible) {
    super.setVisible(visible);
    if (visible) {
        populatePatientComboBox();     // reload patients
        loadMedicinesToComboBox();     // reload medicines too
    }
}

    
    private void loadMedicinesToComboBox() {
    MedicineCB.removeAllItems(); // Clear old items

    MedicineManager medicineManager = MedicineManager.getInstance();

    for (Medicine med : medicineManager.getAllMedicinesFIFO()) {
        MedicineCB.addItem(med.getName() + " (" + med.getDose() + ")");
    }

    if (MedicineCB.getItemCount() == 0) {
        MedicineCB.addItem("No medicines available");
    }
}
private Medicine findMedicineByName(String medicineName) {
    for (Medicine med : medicineManager.getAllMedicinesFIFO()) {
        if (med.getName().equalsIgnoreCase(medicineName)) {
            return med;
        }
    }
    return null;
}

}
