/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controll.Navigator;
import Controll.PrescriptionStore;
import javax.swing.JOptionPane;
import View.AddPatient;

/**
 *
 * @author upash
 */
public class PrescriptionPage extends javax.swing.JPanel {
    
     private final String patientId;
    /**
     * Creates new form PrescriptionPage
     */
    public PrescriptionPage(String patientId) {
    this.patientId = patientId;
    initComponents();
    loadForPatient();

}


// Optional: keep NetBeans default constructor for design preview only
public PrescriptionPage() {
    this.patientId = "";            //  prevent null/compile issues
    initComponents();
}
  
    
    private void loadForPatient() {
    
    // 1. Get the record from store
    PrescriptionStore.Record r =
            PrescriptionStore.getInstance().get(patientId);

    // 2. If nothing saved yet
    if (r == null) {
        UserRecTxtArea.setText("No prescription available yet.");
        MedListUser.setText("");
        return;
    }

    // 3. Populate UI
    UserRecTxtArea.setText(r.doctorPrescription);
    MedListUser.setText(r.medicineDetails);
}
   @Override
public void setVisible(boolean visible) {
    super.setVisible(visible);
    if (visible && patientId != null && !patientId.isBlank()) {
        loadForPatient();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DoctorRecForUser = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserRecTxtArea = new javax.swing.JTextArea();
        MedList = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MedListUser = new javax.swing.JTextArea();
        Home = new javax.swing.JButton();

        setBackground(new java.awt.Color(219, 245, 245));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel1.setText("Prescription Page");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 51, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        DoctorRecForUser.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        DoctorRecForUser.setText("Doctor recommendations:");
        add(DoctorRecForUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 363, -1, -1));

        UserRecTxtArea.setColumns(20);
        UserRecTxtArea.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        UserRecTxtArea.setRows(5);
        jScrollPane1.setViewportView(UserRecTxtArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 402, 460, 397));

        MedList.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        MedList.setText("Medicine List:");
        add(MedList, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, -1, -1));

        MedListUser.setColumns(20);
        MedListUser.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        MedListUser.setRows(5);
        jScrollPane2.setViewportView(MedListUser);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 500, 411));

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 280, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        Navigator.showUserPanel(patientId);
       
    }//GEN-LAST:event_HomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DoctorRecForUser;
    private javax.swing.JButton Home;
    private javax.swing.JLabel MedList;
    private javax.swing.JTextArea MedListUser;
    private javax.swing.JTextArea UserRecTxtArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
