/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.Navigator;

/**
 *
 * @author upash
 */
public class User_Panel extends javax.swing.JPanel {
private final String loggedInPatientId;

    /**
     * Creates new form User_Panel
     */
    public User_Panel(String patientId) {
        this.loggedInPatientId = patientId;
        initComponents();
    }

    public User_Panel() {
        this.loggedInPatientId = "";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Prescription = new javax.swing.JLabel();
        PrescriptionPic = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Logout = new javax.swing.JLabel();
        LogoutUser = new javax.swing.JLabel();

        setBackground(new java.awt.Color(219, 245, 244));
        setMinimumSize(new java.awt.Dimension(1707, 1067));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel2.setText("Welcome User");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, -1, -1));

        jPanel1.setBackground(new java.awt.Color(219, 245, 244));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Prescription.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        Prescription.setText("Prescription");
        Prescription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PrescriptionMouseEntered(evt);
            }
        });
        Prescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PrescriptionKeyPressed(evt);
            }
        });
        jPanel1.add(Prescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        PrescriptionPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UserPanel2.jpg"))); // NOI18N
        PrescriptionPic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrescriptionPicMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PrescriptionPicMouseEntered(evt);
            }
        });
        PrescriptionPic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PrescriptionPicKeyPressed(evt);
            }
        });
        jPanel1.add(PrescriptionPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 640, 460));

        jPanel2.setBackground(new java.awt.Color(219, 245, 244));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logout.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        Logout.setText("Logout");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutMouseEntered(evt);
            }
        });
        jPanel2.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        LogoutUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoutUser.png"))); // NOI18N
        LogoutUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutUserMouseEntered(evt);
            }
        });
        jPanel2.add(LogoutUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 650, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void PrescriptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrescriptionMouseEntered
        // TODO add your handling code here:
        Prescription.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_PrescriptionMouseEntered

    private void PrescriptionPicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrescriptionPicMouseEntered
        // TODO add your handling code here:
        PrescriptionPic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_PrescriptionPicMouseEntered

    private void PrescriptionPicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrescriptionPicMouseClicked
        // TODO add your handling code here:
         Navigator.showPrescriptionPage(loggedInPatientId);
    }//GEN-LAST:event_PrescriptionPicMouseClicked

    private void PrescriptionPicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrescriptionPicKeyPressed
        // TODO add your handling code here:
        if (loggedInPatientId == null || loggedInPatientId.trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Patient ID not set!");
        return;
    }
    Navigator.showPrescriptionPage(loggedInPatientId);
    }//GEN-LAST:event_PrescriptionPicKeyPressed

    private void PrescriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrescriptionKeyPressed
        // TODO add your handling code here:
         if (loggedInPatientId == null || loggedInPatientId.trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Patient ID not set!");
        return;
    }
    Navigator.showPrescriptionPage(loggedInPatientId);
    }//GEN-LAST:event_PrescriptionKeyPressed

    private void LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseEntered
        // TODO add your handling code here:
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_LogoutMouseEntered

    private void LogoutUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutUserMouseEntered
        // TODO add your handling code here:\
        LogoutUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_LogoutUserMouseEntered

    private void LogoutUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutUserMouseClicked
        // TODO add your handling code here:
         java.awt.Window w = javax.swing.SwingUtilities.getWindowAncestor(this);
    if (w != null) w.dispose();     //  close current User_Panel window
        Navigator.showUserLogin();
       
    }//GEN-LAST:event_LogoutUserMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
         java.awt.Window w = javax.swing.SwingUtilities.getWindowAncestor(this);
    if (w != null) w.dispose();     //  close current User_Panel window
        Navigator.showUserLogin();
         
    }//GEN-LAST:event_LogoutMouseClicked
    
 




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel LogoutUser;
    private javax.swing.JLabel Prescription;
    private javax.swing.JLabel PrescriptionPic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
